name: Process Pipelines

on:
  push: {branches: main, paths: pipelines/**}

jobs:
  pipeprocess:
    runs-on: ubuntu-latest
    name: Run script
    steps:
      - uses: actions/checkout@v3
      - run: git branch generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }}
      
      - uses: actions/checkout@v3
        with:
          ref: generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }}
      - run: python .github/workflows/process.py
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Update pipelines_index.json"
          git push
          gh pr create -B main -H generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }} --title 'Update pipelines_index.json' --body 'Update pipelines index'
