# name: Process Pipelines

# on:
#   push: {branches: main}

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     name: Run script
#     steps:
#       - uses: actions/checkout@v3
      
#       - run: python testpy.py
#       - run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git status
#           git add .
#           git commit -m "Auto file creation"
#           git push