name: Process Pipelines

on:
  push: {branches: main, paths: pipelines/**}

jobs:
  pipeprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Create new branch and run script
        uses: actions/checkout@v3
        with:
          ref: main
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
          git branch generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }}
          git push --set-upstream origin generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }}
          git checkout generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }}
          python .github/workflows/process.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Update pipelines_index.json"
          git push
          gh pr create -H main -H generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }} --title 'Update pipelines_index.json' --body 'Update pipelines index'

      # - name: Run script
      #   uses: actions/checkout@v3
      #   with:
      #     ref: generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }}
      # - run: python .github/workflows/process.py
    
      # - name: Push and pull request
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git status
      #     git add .
      #     git commit -m "Update pipelines_index.json"
      #     git push
      #     gh pr create -B main -H generate-file-branch-${{ github.run_id }}-${{ github.run_attempt }} --title 'Update pipelines_index.json' --body 'Update pipelines index'
